# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: agency
    main: ./cmd/agency
    binary: agency
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/NielsdaWheelz/agency/internal/version.Version={{.Version}}

archives:
  - id: agency
    builds:
      - agency
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: NielsdaWheelz
    name: agency
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

# Homebrew tap (uncomment after creating homebrew-tap repo)
# brews:
#   - name: agency
#     repository:
#       owner: NielsdaWheelz
#       name: homebrew-tap
#     homepage: "https://github.com/NielsdaWheelz/agency"
#     description: "Local-first runner manager for AI coding sessions"
#     license: "MIT"
#     install: |
#       bin.install "agency"
#     test: |
#       system "#{bin}/agency", "--version"
