# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...
    # Generate shell completion scripts before build
    # Uses go run to avoid PATH issues in CI - completion generation doesn't depend on ldflags
    - mkdir -p completions
    - go run ./cmd/agency completion bash > completions/agency.bash
    - go run ./cmd/agency completion zsh > completions/_agency

builds:
  - id: agency
    main: ./cmd/agency
    binary: agency
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/NielsdaWheelz/agency/internal/version.Version={{.Version}}
      - -X github.com/NielsdaWheelz/agency/internal/version.Commit={{.ShortCommit}}

archives:
  - id: agency
    builds:
      - agency
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: NielsdaWheelz
    name: agency
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

brews:
  - name: agency
    repository:
      owner: NielsdaWheelz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/NielsdaWheelz/agency"
    description: "Local-first runner manager for AI coding sessions"
    license: "MIT"
    install: |
      bin.install "agency"
      bash_completion.install "completions/agency.bash" => "agency"
      zsh_completion.install "completions/_agency"
    test: |
      system "#{bin}/agency", "--version"
